exports.seed = function (knex) {
  // Deletes ALL existing entries
  return knex("users")
    .del()
    .then(function () {
      // Inserts seed entries
      return knex("users").insert([
        {
          id: 1,
          user_name: "admin",
          password: "admin",
          account_verified: true,
        },
        {
          id: 2,
          user_name: "Morpheus Fishburne",
          password: "teacher1",
          account_verified: true,
        },
        {
          id: 3,
          user_name: "Neo Reeves",
          password: "teacher2",
          account_verified: true,
        },
        {
          id: 4,
          user_name: "Egon Burress",
          password: "PT1G9MiaZ",
          account_verified: false,
        },
        {
          id: 5,
          user_name: "Donnajean de Voiels",
          password: "Jx6Fbg8lSq",
          account_verified: false,
        },
        {
          id: 6,
          user_name: "Tilly Randalson",
          password: "fESf7IvFrd",
          account_verified: false,
        },
        {
          id: 7,
          user_name: "Tiebold Arrell",
          password: "q9PFP4",
          account_verified: false,
        },
        {
          id: 8,
          user_name: "Abagail Sante",
          password: "d0COiBgAsOko",
          account_verified: false,
        },
        {
          id: 9,
          user_name: "Piotr Clarkson",
          password: "EsNk8lU2q",
          account_verified: false,
        },
        {
          id: 10,
          user_name: "Dave Priestner",
          password: "M28eov1xMr",
          account_verified: false,
        },
        {
          id: 11,
          user_name: "Teri Dibben",
          password: "mZpfdSQ5M",
          account_verified: false,
        },
        {
          id: 12,
          user_name: "Allyn Kwietak",
          password: "Sj1GSpE",
          account_verified: false,
        },
        {
          id: 13,
          user_name: "Dede Meek",
          password: "zkfa4CWMcP",
          account_verified: false,
        },
        {
          id: 14,
          user_name: "Clemence Ridwood",
          password: "jXCvVMdsb6Pc",
          account_verified: false,
        },
        {
          id: 15,
          user_name: "Aldridge Franzonetti",
          password: "6q7vjFkIzpUD",
          account_verified: false,
        },
        {
          id: 16,
          user_name: "Monah McCafferky",
          password: "zMXdMNSryV",
          account_verified: false,
        },
        {
          id: 17,
          user_name: "Karlik Staveley",
          password: "ay4ghYmWC1X",
          account_verified: false,
        },
        {
          id: 18,
          user_name: "Carlyle Berns",
          password: "t8rznW3dpWVM",
          account_verified: false,
        },
        {
          id: 19,
          user_name: "Kalil Crebbin",
          password: "BFX2BKpQ",
          account_verified: false,
        },
        {
          id: 20,
          user_name: "Maud Bordone",
          password: "QlmHpSbwTe0l",
          account_verified: false,
        },
        {
          id: 21,
          user_name: "Chastity Lockett",
          password: "80djQiilNr1",
          account_verified: false,
        },
        {
          id: 22,
          user_name: "Catriona Mettrick",
          password: "evGBg8rrKk5e",
          account_verified: false,
        },
        {
          id: 23,
          user_name: "Fidel Lascelles",
          password: "JlIyiUsCn",
          account_verified: false,
        },
        {
          id: 24,
          user_name: "Zea Leadbetter",
          password: "noIovRsLlcS",
          account_verified: false,
        },
        {
          id: 25,
          user_name: "Amelie Kuhne",
          password: "WgXqQK2FFws",
          account_verified: false,
        },
        {
          id: 26,
          user_name: "Dayle Riccardini",
          password: "RyH7upPYlio",
          account_verified: false,
        },
        {
          id: 27,
          user_name: "Marjory Wipfler",
          password: "Lk480jVbfu",
          account_verified: false,
        },
        {
          id: 28,
          user_name: "Rafferty Clifford",
          password: "bAbXerFQ",
          account_verified: false,
        },
        {
          id: 29,
          user_name: "Rourke Felten",
          password: "4YBP9lIymKJP",
          account_verified: false,
        },
        {
          id: 30,
          user_name: "Glennie Essberger",
          password: "R5OZDcnczKua",
          account_verified: false,
        },
        {
          id: 31,
          user_name: "Amandie Phin",
          password: "at5hg1UW3za",
          account_verified: false,
        },
        {
          id: 32,
          user_name: "Lauryn Schulz",
          password: "ezZfg0fwokgn",
          account_verified: false,
        },
        {
          id: 33,
          user_name: "Elias Antyshev",
          password: "4HzsFT",
          account_verified: false,
        },
        {
          id: 34,
          user_name: "Olivero Dulson",
          password: "t037AMovhD",
          account_verified: false,
        },
        {
          id: 35,
          user_name: "Hailey Algie",
          password: "dNgBcJyS",
          account_verified: false,
        },
        {
          id: 36,
          user_name: "Valaree Schenkel",
          password: "PKaarlVcS",
          account_verified: false,
        },
        {
          id: 37,
          user_name: "Teddie Scrivenor",
          password: "zoxDLT0",
          account_verified: false,
        },
        {
          id: 38,
          user_name: "Purcell Brauns",
          password: "ldIfkgh0Vo",
          account_verified: false,
        },
        {
          id: 39,
          user_name: "Rich Bernt",
          password: "u8VC94sQzyx4",
          account_verified: false,
        },
        {
          id: 40,
          user_name: "Noreen Arnet",
          password: "PQncj96X",
          account_verified: false,
        },
        {
          id: 41,
          user_name: "Drucie Wabersich",
          password: "9YdZBKve",
          account_verified: false,
        },
        {
          id: 42,
          user_name: "Marybelle Garlinge",
          password: "eV5dHW",
          account_verified: false,
        },
        {
          id: 43,
          user_name: "Aurel Rodgier",
          password: "3RcoSOc02N2",
          account_verified: false,
        },
        {
          id: 44,
          user_name: "Mildrid Nore",
          password: "iqxUEti1Wlz6",
          account_verified: false,
        },
        {
          id: 45,
          user_name: "Karina Normandale",
          password: "lqwfa3",
          account_verified: false,
        },
        {
          id: 46,
          user_name: "Forrester Tuckett",
          password: "UVHGPy",
          account_verified: false,
        },
        {
          id: 47,
          user_name: "Mahmoud Arne",
          password: "y6d960",
          account_verified: false,
        },
        {
          id: 48,
          user_name: "Ailina Donegan",
          password: "gIWZQ8qg0J",
          account_verified: false,
        },
        {
          id: 49,
          user_name: "Kylie Ravilus",
          password: "wy0oy4itxLU",
          account_verified: false,
        },
        {
          id: 50,
          user_name: "Rhetta Sedgeworth",
          password: "F2cMAL",
          account_verified: false,
        },
        {
          id: 51,
          user_name: "Rutger Grigoriscu",
          password: "pAUyues",
          account_verified: false,
        },
        {
          id: 52,
          user_name: "Estella Keniwell",
          password: "35r1Ddj84u",
          account_verified: false,
        },
        {
          id: 53,
          user_name: "Delmar Dorran",
          password: "KIu4V2",
          account_verified: false,
        },
        {
          id: 54,
          user_name: "Sissie Essel",
          password: "eKhHgZUXgre",
          account_verified: false,
        },
        {
          id: 55,
          user_name: "Doe McMechan",
          password: "2A7d1fN",
          account_verified: false,
        },
        {
          id: 56,
          user_name: "Amitie Stirling",
          password: "DXHXnyBzY",
          account_verified: false,
        },
        {
          id: 57,
          user_name: "Darnell Grasha",
          password: "oMKSk168A",
          account_verified: false,
        },
        {
          id: 58,
          user_name: "Regen Indruch",
          password: "zMHGhIlDI9Y",
          account_verified: false,
        },
        {
          id: 59,
          user_name: "Evy Sabates",
          password: "7KdGwoG51Z",
          account_verified: false,
        },
        {
          id: 60,
          user_name: "Marlane Dobell",
          password: "ipqdjB",
          account_verified: false,
        },
      ]);
    });
};
