
exports.seed = function(knex) {
  // Deletes ALL existing entries
  return knex("class_attendances").del()
    .then(function () {
      // Inserts seed entries
      return knex("class_attendances").insert([
        {
          id: 1,
          class_id: 1,
          user_id: 4,
          attended: true,
          arrived_late: true,
          late_minutes: 4,
          camera_on: true,
          connectivity_issues: true,
          distracted: false,
          comments:
            "est et tempus semper est quam pharetra magna ac consequat metus sapien ut",
        },
        {
          id: 2,
          class_id: 1,
          user_id: 5,
          attended: false,
          arrived_late: false,
          late_minutes: 21,
          camera_on: true,
          connectivity_issues: false,
          distracted: true,
          comments: "in lectus pellentesque at nulla",
        },
        {
          id: 3,
          class_id: 1,
          user_id: 6,
          attended: false,
          arrived_late: false,
          late_minutes: 31,
          camera_on: true,
          connectivity_issues: false,
          distracted: true,
          comments: "cras in purus eu magna",
        },
        {
          id: 4,
          class_id: 1,
          user_id: 7,
          attended: false,
          arrived_late: true,
          late_minutes: 17,
          camera_on: false,
          connectivity_issues: true,
          distracted: true,
          comments:
            "in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis",
        },
        {
          id: 5,
          class_id: 2,
          user_id: 4,
          attended: true,
          arrived_late: false,
          late_minutes: 17,
          camera_on: true,
          connectivity_issues: false,
          distracted: true,
          comments:
            "placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit",
        },
        {
          id: 6,
          class_id: 2,
          user_id: 5,
          attended: true,
          arrived_late: false,
          late_minutes: 16,
          camera_on: true,
          connectivity_issues: true,
          distracted: true,
          comments: "ullamcorper purus sit",
        },
        {
          id: 7,
          class_id: 2,
          user_id: 6,
          attended: true,
          arrived_late: false,
          late_minutes: 5,
          camera_on: false,
          connectivity_issues: false,
          distracted: false,
          comments: "in faucibus orci luctus et ultrices posuere cubilia curae",
        },
        {
          id: 8,
          class_id: 2,
          user_id: 7,
          attended: true,
          arrived_late: false,
          late_minutes: 27,
          camera_on: false,
          connectivity_issues: false,
          distracted: true,
          comments:
            "orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis",
        },
        {
          id: 9,
          class_id: 3,
          user_id: 4,
          attended: true,
          arrived_late: true,
          late_minutes: 17,
          camera_on: false,
          connectivity_issues: true,
          distracted: false,
          comments:
            "imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce",
        },
        {
          id: 10,
          class_id: 3,
          user_id: 5,
          attended: false,
          arrived_late: false,
          late_minutes: 32,
          camera_on: true,
          connectivity_issues: true,
          distracted: false,
          comments:
            "erat curabitur gravida nisi at nibh in hac habitasse platea dictumst aliquam",
        },
        {
          id: 11,
          class_id: 3,
          user_id: 6,
          attended: false,
          arrived_late: true,
          late_minutes: 13,
          camera_on: true,
          connectivity_issues: false,
          distracted: true,
          comments:
            "rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis",
        },
        {
          id: 12,
          class_id: 3,
          user_id: 7,
          attended: false,
          arrived_late: true,
          late_minutes: 26,
          camera_on: true,
          connectivity_issues: true,
          distracted: false,
          comments:
            "elit proin risus praesent lectus vestibulum quam sapien varius",
        },
        {
          id: 13,
          class_id: 4,
          user_id: 4,
          attended: false,
          arrived_late: false,
          late_minutes: 6,
          camera_on: false,
          connectivity_issues: false,
          distracted: false,
          comments: "nisl venenatis lacinia aenean sit",
        },
        {
          id: 14,
          class_id: 4,
          user_id: 5,
          attended: true,
          arrived_late: false,
          late_minutes: 25,
          camera_on: true,
          connectivity_issues: true,
          distracted: false,
          comments: "purus sit amet",
        },
        {
          id: 15,
          class_id: 4,
          user_id: 6,
          attended: true,
          arrived_late: true,
          late_minutes: 30,
          camera_on: true,
          connectivity_issues: true,
          distracted: false,
          comments:
            "condimentum neque sapien placerat ante nulla justo aliquam quis turpis",
        },
        {
          id: 16,
          class_id: 4,
          user_id: 7,
          attended: false,
          arrived_late: true,
          late_minutes: 13,
          camera_on: true,
          connectivity_issues: true,
          distracted: false,
          comments:
            "nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id",
        },
        {
          id: 17,
          class_id: 5,
          user_id: 8,
          attended: true,
          arrived_late: true,
          late_minutes: 8,
          camera_on: false,
          connectivity_issues: true,
          distracted: false,
          comments: "vitae ipsum aliquam non mauris morbi non lectus",
        },
        {
          id: 18,
          class_id: 5,
          user_id: 9,
          attended: true,
          arrived_late: true,
          late_minutes: 23,
          camera_on: true,
          connectivity_issues: true,
          distracted: true,
          comments: "non mauris morbi non",
        },
        {
          id: 19,
          class_id: 5,
          user_id: 10,
          attended: false,
          arrived_late: true,
          late_minutes: 27,
          camera_on: true,
          connectivity_issues: true,
          distracted: false,
          comments:
            "cum sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus mus vivamus vestibulum sagittis",
        },
        {
          id: 20,
          class_id: 5,
          user_id: 11,
          attended: true,
          arrived_late: true,
          late_minutes: 34,
          camera_on: true,
          connectivity_issues: true,
          distracted: false,
          comments: "in sagittis dui vel nisl duis ac nibh fusce lacus purus",
        },
        {
          id: 21,
          class_id: 6,
          user_id: 8,
          attended: true,
          arrived_late: true,
          late_minutes: 1,
          camera_on: false,
          connectivity_issues: true,
          distracted: true,
          comments: "augue vestibulum rutrum rutrum neque aenean auctor",
        },
        {
          id: 22,
          class_id: 6,
          user_id: 9,
          attended: false,
          arrived_late: true,
          late_minutes: 22,
          camera_on: true,
          connectivity_issues: true,
          distracted: true,
          comments:
            "velit nec nisi vulputate nonummy maecenas tincidunt lacus at velit vivamus vel nulla eget eros",
        },
        {
          id: 23,
          class_id: 6,
          user_id: 10,
          attended: true,
          arrived_late: false,
          late_minutes: 18,
          camera_on: true,
          connectivity_issues: false,
          distracted: true,
          comments: "in ante vestibulum ante ipsum primis",
        },
        {
          id: 24,
          class_id: 6,
          user_id: 11,
          attended: false,
          arrived_late: true,
          late_minutes: 18,
          camera_on: false,
          connectivity_issues: false,
          distracted: true,
          comments: "nec sem duis aliquam convallis",
        },
        {
          id: 25,
          class_id: 7,
          user_id: 12,
          attended: true,
          arrived_late: false,
          late_minutes: 2,
          camera_on: false,
          connectivity_issues: true,
          distracted: false,
          comments: "ornare consequat lectus",
        },
        {
          id: 26,
          class_id: 7,
          user_id: 13,
          attended: true,
          arrived_late: false,
          late_minutes: 31,
          camera_on: false,
          connectivity_issues: false,
          distracted: true,
          comments:
            "eu interdum eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla",
        },
        {
          id: 27,
          class_id: 7,
          user_id: 14,
          attended: false,
          arrived_late: false,
          late_minutes: 15,
          camera_on: true,
          connectivity_issues: false,
          distracted: true,
          comments: "natoque penatibus et magnis",
        },
        {
          id: 28,
          class_id: 7,
          user_id: 15,
          attended: true,
          arrived_late: true,
          late_minutes: 36,
          camera_on: false,
          connectivity_issues: true,
          distracted: false,
          comments: "ante ipsum primis in faucibus orci",
        },
        {
          id: 29,
          class_id: 8,
          user_id: 12,
          attended: true,
          arrived_late: false,
          late_minutes: 26,
          camera_on: true,
          connectivity_issues: false,
          distracted: false,
          comments: "pellentesque eget nunc",
        },
        {
          id: 30,
          class_id: 8,
          user_id: 13,
          attended: false,
          arrived_late: false,
          late_minutes: 11,
          camera_on: false,
          connectivity_issues: true,
          distracted: true,
          comments: "augue vel accumsan tellus nisi eu orci",
        },
        {
          id: 31,
          class_id: 8,
          user_id: 14,
          attended: false,
          arrived_late: true,
          late_minutes: 38,
          camera_on: false,
          connectivity_issues: false,
          distracted: true,
          comments:
            "fermentum donec ut mauris eget massa tempor convallis nulla neque",
        },
        {
          id: 32,
          class_id: 8,
          user_id: 15,
          attended: true,
          arrived_late: false,
          late_minutes: 3,
          camera_on: true,
          connectivity_issues: true,
          distracted: true,
          comments:
            "quam pede lobortis ligula sit amet eleifend pede libero quis orci nullam",
        },
      ]);
    });
};
